<img src="assets/ostopathe-enfant.jpg" alt="osteophate avec un enfant"></img>

<h2>Pourquoi consulter un ostéophathe pour son nourrisson</h2>
<p>Après un accouchement, il est recommandé de consulter un osthéophe si:</p>
    <ul>
        <li>Vous avez accouché sous péridurale,</li>
        <li>En cas de grossesse gémellaire (jumeaux),</li>
        <li>Si votre accouchement a dépasse huit heures, ou au contraire a duré moins de deux heures,</li>
        <li>Si la présentation s'est faite par le front ou en siège,</li>
        <li>SI votre bébé est prématuré,</li>
        <li>SI le medecin a utilisé des spatules, des ventouses ou des forceps ou s'il y a eu une césarienne,</li>
        <li>Si le cordon s'est enroulé autour du cou du bébé ou s'il y a eu souffrance fœtale ou réanimation, même légère , de votre enfant.</li>
    </ul>

<p>Les signes du nourrisson nécessitant un traitement ostéopathique sont les suivants:</p>
    <ul>
        <li>Le bébé pleure presque tout le temps, il dort très peu, il régurgite, digère mal et est souvent agité après la tétée,</li>
        <li>Il tourne la tête toujours d'un seul coté ou positionne son corps en banane accompagné ou non d'un crane aplati sur un coté,</li>
        <li>Il présente des troubles à à répétition de type bronchiolites, respiration bruyante ou otites.</li>
    </ul>
    
<p>Par un examen très doux, l'ostéophate repèrera et remédira aux dysfonctionnement mineurs provoquant les troubles? les mains de 
l'ostéopathe permettront à votre nouveau-né de retrouver toute sa joie de vivre.</p>

<p>N'hésitez pas à m'appeler au cas où vous souhaiteriez un complement d'information ou bien convenir d'un premier rendez-vous.</p>