<h2>qui suis-je?</h2>
    <p>Installé depuis octobre 2013 au sein du Centre de Santé Clément Viénot en tant qu’ostéopathe, j’y accueille tous les patients du nourrisson au sénior.</p>
    <p>J’ai effectué mes études au sein de l’Institut Dauphine d’Ostéopathie de Paris au cours desquelles j’ai travaillé dans le Centre Ostéopathique des Halles de de 2010 à 2013. Durant mes années d’études, j’ai participé à de nombreux stages sportifs au sein de club de football et d’athlétisme. A la fin de mes études après l’obtention de mon Diplôme d’Ostéopathie en 2013, j’ai continué à suivre l’équipe de Handball de Rosny-Sous-Bois durant 2 ans.</p>
    <p>Footballeur durant mes jeunes années, je pratique aujourd’hui le triathlon ce qui me donne une sensibilité particulière à tout ce qui touche le domaine du sport et à l’ostéopathie.</p>
    <p>La préparation physique, la rééducation et l’étude du geste dans le sport sont des domaines qui me fascinent et m’apporte beaucoup dans ma pratique. J’ai effectué au départ dans l’optique d’apporter un plus à mes patients sportifs un Diplôme Universitaire de Nutrition et de Micronutrition à l’Université de Dijon en 2015 qui m’aide finalement pour la prise en charge de tous mes patients au quotidien.</p>
    <p>Depuis le début de mon installation à Vincennes, je partage mon cabinet avec une Sage-Femme ce qui m’a amené à voir beaucoup de nourrissons et de femmes enceintes en consultation et donc m’a poussé à faire en 2015 la formation en ostéopathie pédiatrie et crânienne OstéoBébe de Mr Simon et Mme Heintz Blondy.</p>
    <p>Mes consultations d’ostéopathie durent environ 45 minutes à 1heure. La séance débute par une série de questions pour mieux connaitre mon patient et comprendre le motif de consultation, s’ensuit une phase d’observation et de tests pour comprendre « ce qui fait mal » ainsi qu’analyser les restrictions de mobilité, puis le traitement en lui-même pour lever les restrictions, enfin je reteste pour évaluer les progrès et vérifier si le travail est terminé.</p>
    <p>Si je devais résumer mes consultations d’ostéopathie en un seul mot, ce serait : Mobilité. La  chose la plus importante est que votre corps retrouve la mobilité dans sa globalité  pour retrouver son équilibre.</p>
    <p>Durant mes séances j’aime expliquer ce que je fais clairement. Pour moi, le patient doit sortir de ma séance en sachant expliquer ce que j’ai fait et pourquoi je l’ai fait.</p>

<h3>Mes formations</h3>

<ul>
    <li>2015 – Formation en pédiatrie / Paris</li>
    <li>2015 – Diplôme universitaire Nutrition - Micro-nutrition / Paris</li>
    <li>2013 – Diplôme d’ostéopathe (D.O) / Paris</li>
</ul>