<article>
          <iframe autoplay muted loop width="auto" height="auto" src="https://www.youtube.com/embed/G0NwvXBWtek" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </article>
            <section>
                <article>
                  <h1>le cabinet de jeremy</h1>
                    <h2>Qu’est-ce que l’ostéopathie ?</h2>
                      <p>Créée le 22 juin 1874 par le médecin américain Andrew Taylor Still, elle se définit comme:</p>
                      <p>« Une science thérapeutique naturelle, fondée sur une connaissance précise de l'anatomie et de la physiologie du corps humain.</p>
                      <p>Elle utilise tout moyen diagnostique dans le but de mettre en évidence les dysfonctionnements, l'absence de mobilité des tissus entraînant une altération de l'équilibre de santé.</p>
                      <p>Le concept ostéopathique, dans sa pratique uniquement manuelle, sollicite au mieux les ressources inhérentes de l'individu, considéré dans sa globalité et reconsidéré dans son environnement. »</p>
                      <p>L’Ostéopathe choisira la technique la mieux adaptée et la plus confortable pour chaque patient, en fonction de son âge, de sa morphologie et de la zone du corps à corriger. Il peut traiter le nourrisson, l’enfant, l’adulte comme la personne âgée. </p>
                      <p>L'Ostéopathie connaît de vastes champs d'application, elle est efficace dans de nombreux domaines comme sur les structures articulaires, musculaires, ainsi que sur les structures tissulaires.</p>
                </article>
                 <article>
                  <h2>Pourquoi consulter ? </h2>
                    <p>L'ostéopathie s'adresse aux nourrissons, aux enfants, aux adultes, aux sportifs, aux femmes enceintes et aux personnes âgées. Cette classification est justifiée par la différence chez ces personnes, dans leur anatomie, dans leur physiologie, dans la qualité de leurs tissus et dans les contraintes auxquelles elles doivent s'adapter.</p>
                    <p>L’ostéopathe tous types de troubles fonctionnels :</p>
                    <ul>
                        <li>De l'appareil locomoteur : cervicalgies, torticolis, dorsalgies, douleurs intercostales, lumbago, névralgies, entorses, accidents musculaires, tendinites, conséquences des coups du lapin, maux de tête d'origine mécanique.</li>
                        <li>Du système neurovégétatif : dystonie neurovégétative.</li>
                        <li>Du système digestif : dysphagie, gastralgie, reflux gastro-oesophagien, dyspepsies, dyspéristaltisme intestinal, régurgitations, nausées.</li>
                        <li>Du système génito-urinaire : dysménorrhées fonctionnelles, dyspareunies mécaniques, dysurie, prévention des infections urinaires.</li>
                        <li>De la bouche et de la sphère ORL : dysphonie fonctionnelle, préventions des sinusites et otites répétitives, vertiges fonctionnels.</li>
                        <li>Du système respiratoire : dysphrénie fonctionnelle, prévention des bronchites répétitives.</li>
                        <li>Ainsi que les manifestations rencontrées par le bébé après la naissance : troubles du sommeil, agitation, régurgitations, coliques, plagiocéphalies …</li>
                    </ul>
                    <p>L'ostéopathie est également susceptible d'apporter un bénéfice lors de :</p>
                    <ul>
                        <li>L'accompagnement de la grossesse et du post-partum.</li>
                        <li>L'accompagnement des suites d'intervention chirurgicale notamment en cas de thoracotomie et laparotomie.</li>
                        <li>L'accompagnement des traitements orthodontiques.</li>
                        <li>L'accompagnement des traitements des pathologies orthopédiques de l'enfance et de l'adolescence (pied bot, torticolis congénital, scoliose, cyphose…).</li>
                    </ul>
        </article>
    </section>

    <article>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d168036.1119851639!2d2.2149098474586535!3d48.84744987012229!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e672ac3b72432d%3A0x525cb45da2a43e69!2zSsOpcsOpbXkgQ29oZW4!5e0!3m2!1sfr!2sfr!4v1609751383364!5m2!1sfr!2sfr" width="100%" height="auto"  style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>

    </article>