<link rel="stylesheet" href="css/main.css" type="text/css" />
<h2>quels conseils désirez-vous</h2>

<section class="grid">
    <a class='bebe' href="#"><img  src="www/assets/bebe.jpg" alt="bebe"></img></a>
    <a class='enceinte' href="#"><img src="assets/enceinte.jpg" alt="enceinte"></img></a>
    <a class='lombalgie' href="#"><img src="assets/lombalgie.jpg" alt="lombalgie"></img></a>
    <a class='migraine' href="#"><img  src="assets/migraine.jpg" alt="migraine"></img></a>
    <a class='nutrition' href="#"><img src="assets/nutrition.jpg" alt="nutrition"></img></a>
    <a class='post' href="#"><img src="assets/post-op.jpg" alt="post-op"></img></a>
    <a class='sport' href="#"><img src="assets/sport.jpg" alt="sport"></img></a>
    <a class='strap' href="#"><img src="assets/strap.jpg" alt="strap"></img></a>
</section>