<img src="assets/osteo-pregnant.jpg" alt="femme enceinte"></img>
<h2>Ostéopathe pour femme enceinte</h2>

<p>Notre cabinet réalise des consultations spécifiques pour le traitement de la future maman.</p>

<p>La grossesse produit des transformations importantes dans votre corps. Des évolutions hormonales 
vont entraîner des modifications sur les tissus de votre corps. Ils deviennent plus souples pendant 
la grossesse pour permettre le passage du bébé au niveau du bassin.</p>

<p>La forme et le poids de votre ventre vont provoquer une modification de posture. Votre centre de gravité 
va bouger et se retrouver plus en avant. Par ailleurs, la grossesse va causer une augmentation de la pression 
au niveau de la cavité abdominale les viscères devront alors trouver une nouvelle place.</p>

<p>Toutes ces transformations vont être à l'origine de nombreux dysfonctionnements entrainant des 
douleurs que l'ostéopathe saura soulager.</p>

<p>Au fond, une femme enceinte peut avoir recours à un ostéopathe pour une variété de symptômes : 
mécaniques, mais aussi digestives, circulatoires, etc. Les douleurs mécaniques, comme les lombalgies, 
sont dues à tous les changements qui apparaissent pendant la grossesse. La prise de poids et les forces 
antérieures qui viennent tirer sur la région lombaire (insertions des fascias sur les vertèbres) augmentent 
la lordose lombaire. Les cas de sciatalgie ou sciatique sont aussi fréquents chez la femme enceinte. 
Le nerf sciatique subit un pincement à l'origine de la douleur. Il peut être comprimé lors de son passage dans le muscle pyramidal. 
Les douleurs du coccyx et du bassin sont aussi assez fréquentes.</p>

<p>Une femme enceinte pourra aussi avoir recours à un ostéopathe en raison de troubles digestifs comme des constipations, des ballonnements, 
des diarrhées, des reflux gastriques ou des régurgitations.</p>

<p>Vous avez aussi intérêt à aller chez l'ostéopathe lorsque vous attendez un enfant pour des problèmes circulatoires, 
à savoir des migraines, des œdèmes au niveau des membres inférieurs ou des sensations de lourdeur au niveau des jambes.</p>

<p>Même en l'absence de troubles spécifiques, une femme enceinte a intérêt à consulter un ostéopathe à titre préventif. 
Une telle consultation permet de prévenir la survenance des troubles évoqués ci-dessus et de recevoir une préparation à l'accouchement.</p>

<p>Pour commencer, l'ostéopathe va observer la patiente pour étudier comment elle se tient et examiner ses courbures.
Il va ensuite s'intéresser spécialement aux articulations au niveau du bassin et identifier des problèmes ou blocages potentiels. 
Il va enfin vérifier si les mobilités du thorax, de l'abdomen et des structures crâniennes sont bonnes.</p>

<p>Toutes les techniques employées par l'ostéopathe sont adaptées à chaque patiente et à chaque contexte de consultation. 
Elles sont bien entendu non invasives pour le bébé. Dès le troisième mois, l'ostéopathe peut être consulté à titre préventif. 
En effet, en général les douleurs apparaissent à partir du 6ème mois de grossesse. Une à deux consultations sont alors nécessaires 
pour traiter la cause des douleurs, puis une à deux consultations permettent de préparer l'accouchement.</p>

<p>Vous pouvez nous joindre au cas où vous souhaiteriez davantage d'informations ou bien convenir d'un premier rendez-vous.</p>