<h3>Enregistrez vous !</h3>
	<form class="b-form" action="../controllers/RegisterController.php" method="POST">
		<input type="text" name="firstname" placeholder="Prénom">
		<input type="text" name="lastname" placeholder="Nom">
		<input type="text" name="email" placeholder="Email">
		<input type="text" name="phone" placeholder="Phone">
		<input type="text" name="password" placeholder="Mot de passe">
		<input type="submit" value="Enregister">
	</form>
