<h2>Honoraires du cabinet</h2>
 <img src="assets/tarif.jpg" alt="tarif"></img>
<p>Les honoraires de consultation sont de 60 euros pour une consultation d'une durée d'environ 45 minutes.</p>
<p>L'ostéopathie, qu'elle soit réalisée par un ostéopathe exclusif, un kiné-ostéopathe ou un médecin-ostéopathe 
n'est jamais remboursée par la sécurité sociale.</p>
<p>En revanche plus de 85% des mutuelles remboursent les actes ostéopathique, ce pourcentage augmente d'année en année.</p>
<p>A la fin de la séance, l'ostéopathe vous délivrera une facture, il ne vous restera plus qu'à envoyer celle ci auprès de votre 
mutuelle qui procédera au remboursement.</p>